### ISSUE TITLE
XMPP.h file not found

### ISSUE THREAD

**Issue by orkhanalizade** [nemesit/SwiftXMPP#7]
How can I fix this error? I searched a lot, but did not find the solution

**Comment by RishiAgar** [comment]
Hey, did you found the solution?

**Comment by orkhanalizade** [comment]
yes. I found. Thanks for response!

**Comment by kenyiu** [comment]
@orkhanalizade mind sharing how to fix the issue? Am facing the same error

**Comment by jessjpj** [comment]
@orkhanalizade I am also facing the same issue. Can you please share the solution.?

**Comment by orkhanalizade** [comment]
@jessjpj I do not recommend you use this framework.

**Comment by jessjpj** [comment]
Then which framework you are recommending?
